import pg from 'pg';
import nodemailer from 'nodemailer';
import webpush from 'web-push';
const {Pool}=pg;
const pool=new Pool({connectionString:process.env.DATABASE_URL||'postgres://kwd_rate:kwd_rate_dev@localhost:5432/kwd_rate'});
const q=async(sql,args=[])=> (await pool.query(sql,args)).rows;
const env=(k,d='')=>process.env[k]||d;
function inQuietHours(start,end){const now=new Date(); const mins=now.getUTCHours()*60+now.getUTCMinutes()+180; const m=((mins%1440)+1440)%1440; const [sh,sm]=String(start).slice(0,5).split(':').map(Number); const [eh,em]=String(end).slice(0,5).split(':').map(Number); const a=sh*60+sm,b=eh*60+em; return a===b?false:(a<b?m>=a&&m<b:m>=a||m<b);}
function setupPush(){ if(env('VAPID_PUBLIC_KEY')&&env('VAPID_PRIVATE_KEY')) webpush.setVapidDetails(env('VAPID_SUBJECT','mailto:alerts@kwdrate.com'),env('VAPID_PUBLIC_KEY'),env('VAPID_PRIVATE_KEY')); }
function mailer(){ if(!env('SMTP_HOST')) return null; return nodemailer.createTransport({host:env('SMTP_HOST'),port:Number(env('SMTP_PORT','587')),secure:env('SMTP_SECURE','false')==='true',auth:env('SMTP_USER')?{user:env('SMTP_USER'),pass:env('SMTP_PASS')}:undefined}); }
async function sendEmail(n){const t=mailer(); if(!t) throw Error('SMTP is not configured'); const info=await t.sendMail({from:env('MAIL_FROM','KWD Rate <alerts@kwdrate.com>'),to:n.destination,subject:n.subject,text:n.body,html:`<div dir="rtl" style="font-family:Arial,sans-serif"><h2>${n.subject}</h2><p>${String(n.body).replace(/\n/g,'<br>')}</p></div>`}); return {provider:'smtp',id:info.messageId};}
async function sendPush(n){setupPush(); if(!env('VAPID_PUBLIC_KEY')||!env('VAPID_PRIVATE_KEY')) throw Error('Web Push VAPID keys are not configured'); const subs=await q('SELECT * FROM push_subscriptions WHERE user_id=$1',[n.user_id]); if(!subs.length) throw Error('No push subscription'); let last=null; for(const s of subs){try{await webpush.sendNotification({endpoint:s.endpoint,keys:{p256dh:s.p256dh,auth:s.auth}},JSON.stringify({title:n.subject,body:n.body,url:'/account.html',notification_id:n.id})); await q('UPDATE push_subscriptions SET last_used_at=NOW() WHERE id=$1',[s.id]); last='web-push';}catch(e){if([404,410].includes(e.statusCode)) await q('DELETE FROM push_subscriptions WHERE id=$1',[s.id]); else throw e;}} if(!last) throw Error('Push delivery failed'); return {provider:last};}
async function sendWhatsApp(n){const token=env('WHATSAPP_ACCESS_TOKEN'),phoneId=env('WHATSAPP_PHONE_NUMBER_ID'); if(!token||!phoneId) throw Error('WhatsApp Cloud API is not configured'); if(!n.destination) throw Error('WhatsApp phone is missing'); const r=await fetch(`https://graph.facebook.com/v23.0/${phoneId}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:n.destination,type:'text',text:{preview_url:false,body:`${n.subject}\n\n${n.body}`}})}); const d=await r.json(); if(!r.ok) throw Error(d?.error?.message||`WhatsApp ${r.status}`); return {provider:'whatsapp',id:d?.messages?.[0]?.id};}
async function dispatch(limit=50){const rows=await q(`SELECT n.*,u.email,u.full_name,p.email_enabled,p.push_enabled,p.whatsapp_enabled,p.whatsapp_phone,p.quiet_hours_enabled,p.quiet_start,p.quiet_end FROM notification_outbox n JOIN users u ON u.id=n.user_id LEFT JOIN notification_preferences p ON p.user_id=n.user_id WHERE n.status='PENDING' AND n.available_at<=NOW() ORDER BY n.id LIMIT $1`,[limit]); let sent=0,failed=0;
 for(const n of rows){let result; try{ if(n.channel==='IN_APP'){await q("UPDATE notification_outbox SET status='DELIVERED',sent_at=NOW(),attempts=attempts+1,provider='in_app' WHERE id=$1",[n.id]);sent++;continue;} if(n.quiet_hours_enabled && n.quiet_start && n.quiet_end && inQuietHours(n.quiet_start,n.quiet_end)) { continue; } if(n.channel==='EMAIL'){if(n.email_enabled===false) throw Error('Email notifications disabled'); result=await sendEmail(n);} else if(n.channel==='PUSH'){if(n.push_enabled===false) throw Error('Push notifications disabled'); result=await sendPush(n);} else if(n.channel==='WHATSAPP'){if(n.whatsapp_enabled===false) throw Error('WhatsApp notifications disabled'); await q('UPDATE notification_outbox SET destination=$2 WHERE id=$1 AND (destination IS NULL OR destination=\'\')',[n.id,n.whatsapp_phone]); const fresh=(await q('SELECT * FROM notification_outbox WHERE id=$1',[n.id]))[0]; result=await sendWhatsApp(fresh);} else if(n.channel==='WEBHOOK'){continue;} else throw Error(`Unsupported channel ${n.channel}`); await q(`UPDATE notification_outbox SET status='DELIVERED',sent_at=NOW(),attempts=attempts+1,last_error=NULL,provider=$2,provider_message_id=$3 WHERE id=$1`,[n.id,result?.provider||'unknown',result?.id||null]); sent++; }
 catch(e){failed++; await q(`UPDATE notification_outbox SET attempts=attempts+1,last_error=$2,status=CASE WHEN attempts+1>=5 THEN 'FAILED' ELSE 'PENDING' END,available_at=NOW()+((attempts+1)*5*INTERVAL '1 minute') WHERE id=$1`,[n.id,e.message]);}}
 return {sent,failed,queued:rows.length}; }
if(process.argv.includes('--once')) dispatch().then(x=>{console.log(JSON.stringify(x));pool.end()}).catch(e=>{console.error(e);pool.end().finally(()=>process.exit(1))});
export {dispatch};
